# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import p2p_pb2 as p2p__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in p2p_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CommandServiceStub(object):
    """=========================================================
    APPLICATION -> P2P (COMMAND SUBMISSION)
    =========================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitCommand = channel.unary_unary(
                '/p2p.CommandService/SubmitCommand',
                request_serializer=p2p__pb2.CommandRequest.SerializeToString,
                response_deserializer=p2p__pb2.CommandResponse.FromString,
                _registered_method=True)


class CommandServiceServicer(object):
    """=========================================================
    APPLICATION -> P2P (COMMAND SUBMISSION)
    =========================================================
    """

    def SubmitCommand(self, request, context):
        """Submit a command to the Raft cluster.
        Only the leader will accept.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommandServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitCommand,
                    request_deserializer=p2p__pb2.CommandRequest.FromString,
                    response_serializer=p2p__pb2.CommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'p2p.CommandService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('p2p.CommandService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CommandService(object):
    """=========================================================
    APPLICATION -> P2P (COMMAND SUBMISSION)
    =========================================================
    """

    @staticmethod
    def SubmitCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p.CommandService/SubmitCommand',
            p2p__pb2.CommandRequest.SerializeToString,
            p2p__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RaftServiceStub(object):
    """=========================================================
    RAFT NODE <-> NODE (INTERNAL ONLY)
    =========================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AppendEntries = channel.unary_unary(
                '/p2p.RaftService/AppendEntries',
                request_serializer=p2p__pb2.AppendEntriesRequest.SerializeToString,
                response_deserializer=p2p__pb2.AppendEntriesResponse.FromString,
                _registered_method=True)
        self.RequestVote = channel.unary_unary(
                '/p2p.RaftService/RequestVote',
                request_serializer=p2p__pb2.RequestVoteRequest.SerializeToString,
                response_deserializer=p2p__pb2.RequestVoteResponse.FromString,
                _registered_method=True)
        self.InstallSnapshot = channel.unary_unary(
                '/p2p.RaftService/InstallSnapshot',
                request_serializer=p2p__pb2.InstallSnapshotRequest.SerializeToString,
                response_deserializer=p2p__pb2.InstallSnapshotResponse.FromString,
                _registered_method=True)


class RaftServiceServicer(object):
    """=========================================================
    RAFT NODE <-> NODE (INTERNAL ONLY)
    =========================================================
    """

    def AppendEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InstallSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RaftServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AppendEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntries,
                    request_deserializer=p2p__pb2.AppendEntriesRequest.FromString,
                    response_serializer=p2p__pb2.AppendEntriesResponse.SerializeToString,
            ),
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=p2p__pb2.RequestVoteRequest.FromString,
                    response_serializer=p2p__pb2.RequestVoteResponse.SerializeToString,
            ),
            'InstallSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.InstallSnapshot,
                    request_deserializer=p2p__pb2.InstallSnapshotRequest.FromString,
                    response_serializer=p2p__pb2.InstallSnapshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'p2p.RaftService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('p2p.RaftService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RaftService(object):
    """=========================================================
    RAFT NODE <-> NODE (INTERNAL ONLY)
    =========================================================
    """

    @staticmethod
    def AppendEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p.RaftService/AppendEntries',
            p2p__pb2.AppendEntriesRequest.SerializeToString,
            p2p__pb2.AppendEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p.RaftService/RequestVote',
            p2p__pb2.RequestVoteRequest.SerializeToString,
            p2p__pb2.RequestVoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InstallSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p.RaftService/InstallSnapshot',
            p2p__pb2.InstallSnapshotRequest.SerializeToString,
            p2p__pb2.InstallSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
