apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    spec:
      containers:
      - name: api-gateway
        env:
        - name: NAMESPACE
          value: hospital-h4
        - name: GRPC_TIMEOUT
          value: "30.0"
        - name: P2P_TIMEOUT
          value: "30.0"
