apiVersion: v1
kind: Service
metadata:
  name: hospital-headless
  labels:
    app: hospital
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: hospital
  ports:
  - name: raft
    port: 7001
    targetPort: 7001
